# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
              users:
                vasia:
                    password: $2y$13$sftI8EpjatS94DfjmOW48.yjKxC.Yt.blcZFfW.y7cQoPHSqFPwOC
                    roles: 'ROLE_USER'
        webservice:
            id: app.webservice_user_provider

    encoders:
            AppBundle\Security\User\WebserviceUser: bcrypt
            Symfony\Component\Security\Core\User\User: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:

            anonymous: ~
            provider: webservice
            form_login:
                login_path: login
                check_path: login

            logout:
                path:   /logout
                target: /login

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:

       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/, role: ROLE_USER }
