# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    providers:
        in_memory:
            memory:
              users:
                vasia:
                    password: $2y$13$sftI8EpjatS94DfjmOW48.yjKxC.Yt.blcZFfW.y7cQoPHSqFPwOC
                    roles: 'ROLE_USER'
        webservice:
            id: app.webservice_user_provider

    encoders:
            AppBundle\Security\User\WebserviceUser: bcrypt
            Symfony\Component\Security\Core\User\User: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:

            anonymous: ~
            provider: webservice
            form_login:
                login_path: login
                check_path: login

            logout:
                path:   /logout
                target: /login

    access_control:

       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/, role: ROLE_USER }
