# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    user.file.finder:
            class: Symfony\Component\Finder\Finder
            calls:
                - [in, ['%userdata_path%']]
                - [files, []]
                - [name, ['%userdata_file%']]

    app.webservice_user_provider:
        class: AppBundle\Security\User\WebserviceUserProvider
        arguments: ["@user.file.finder"]